import type { Manuscript } from '@/types/manuscript'

export const initialMockManuscripts: Manuscript[] = [
  {
    id: "1",
    msid: "EMBO-2024-001",
    receivedDate: "2024-01-15",
    title: "Structural basis of ATP hydrolysis by the molecular chaperone Hsp70",
    authors: "Smith, J., Johnson, M., Williams, K.",
    doi: "10.15252/embj.2024001",
    accessionNumber: "PDB-8ABC",
    assignedTo: "Dr. Sarah Chen",
    status: "Under Review",
    workflowState: "in-review",
    priority: "high",
    hasErrors: false,
    hasWarnings: false,
    notes: "High-priority manuscript with excellent figures. Structural data looks comprehensive.",
    lastModified: "2024-01-20T10:30:00Z",
    displayStatus: "Under Review",
    badgeVariant: "default",
    isMapped: true,
    unmappedFields: []
  },
  {
    id: "2", 
    msid: "EMBO-2024-002",
    receivedDate: "2024-01-18",
    title: "CRISPR-Cas9 mediated genome editing in primary human T cells",
    authors: "Brown, A., Davis, L., Miller, R.",
    doi: "10.15252/embj.2024002",
    assignedTo: "Dr. Michael Rodriguez", 
    status: "Pending Review",
    workflowState: "pending",
    priority: "medium",
    hasErrors: false,
    hasWarnings: true,
    notes: "Awaiting reviewer assignment. Some minor formatting issues in figures.",
    lastModified: "2024-01-19T14:45:00Z",
    displayStatus: "Pending Review",
    badgeVariant: "secondary",
    isMapped: true,
    unmappedFields: []
  },
  {
    id: "3",
    msid: "EMBO-2024-003", 
    receivedDate: "2024-01-20",
    title: "Mitochondrial dynamics regulate cellular metabolism during stress",
    authors: "Garcia, C., Wilson, T., Anderson, P.",
    status: "Ready for Publication",
    workflowState: "ready",
    priority: "high",
    hasErrors: false,
    hasWarnings: false,
    notes: "All reviews completed. Ready for final production.",
    lastModified: "2024-01-22T09:15:00Z",
    displayStatus: "Ready for Publication",
    badgeVariant: "default",
    isMapped: true,
    unmappedFields: []
  },
  {
    id: "4",
    msid: "EMBO-2024-004",
    receivedDate: "2024-01-22",
    title: "Single-cell RNA sequencing reveals novel cell types in human brain",
    authors: "Thompson, S., Martinez, E., Clark, D.",
    doi: "10.15252/embj.2024004",
    status: "On Hold",
    workflowState: "on-hold",
    priority: "low",
    hasErrors: true,
    hasWarnings: false,
    notes: "Waiting for authors to address reviewer comments. Data quality issues identified.",
    lastModified: "2024-01-25T16:20:00Z",
    displayStatus: "On Hold",
    badgeVariant: "secondary",
    isMapped: true,
    unmappedFields: []
  },
  {
    id: "5",
    msid: "EMBO-2024-005",
    receivedDate: "2024-01-25",
    title: "Epigenetic regulation of stem cell differentiation",
    authors: "Lee, H., White, J., Taylor, N.",
    assignedTo: "Dr. Sarah Chen",
    status: "Under Review",
    workflowState: "in-review",
    priority: "urgent",
    hasErrors: false,
    hasWarnings: false,
    notes: "Fast-track submission. Requires immediate attention.",
    lastModified: "2024-01-26T11:00:00Z",
    displayStatus: "Under Review",
    badgeVariant: "destructive",
    isMapped: true,
    unmappedFields: []
  }
]

export const WORKFLOW_TABS = [
  { id: 'all', label: 'All Manuscripts', count: 0 },
  { id: 'pending', label: 'Pending Review', count: 0 },
  { id: 'in-review', label: 'In Review', count: 0 },
  { id: 'ready', label: 'Ready', count: 0 },
  { id: 'completed', label: 'Completed', count: 0 }
]